#CONTAGEM REGRESSIVA DE 10seg PARA O ESTOURO DE FOGOS DE ARTIFÍCIO COM UMA PAUSA DE 01seg ENTRE ELES
from time import sleep
for c in range(10, -1, -1): #O TERCEIRO TERMO DEFINE DE QUANTO EM QUANTO VAI SER A CONTAGEM (SOMENTE NECESSÁRIO NA CONTAGEM REGRESSIVA)
    sleep(0.5)              #OU SE FOR FAZER UMA CONTAGEM DE 02 EM 02, 03 EM 03 etc...
    print(c)
print('FELIZ ANO NOVO!!!!!')
print('BOOOM POW BOOOOOOOOOOOOOOOOOOOM PAPAPA')
