#PROGRAMA QUE CALCULA A SOMA ENTRE TODOS OS NÚMEROS IMPARES QUE SÃO MÚLTIPLOS DE 03 DE 01 A 500
soma = 0
cont = 0
for c in range(1, 501, 2): #CONTAGEM A PARTIR DE 1 PARA OS PRÓXIMOS SEREM IMPAR
    if c % 3 == 0: #VERIFICA SE OS NÚMEROS SÃO DIVISÍVEIS POR 3
        cont = cont + 1 #CONTADOR DE QUANTOS NÚMEROS FORAM SOMADOS PARA DAR O RESULTADO
        soma = soma + c #NOVO VALOR DE SOMA NA CONDIÇÃO DE REPETIÇÃO PRA DEMONSTRAR O VALOR TOTAL
print('A soma de {} valores é {}'.format(cont, soma))
