# O COMANDO 'IMPORT' É O QUE DISPONIBILIZA AS BIBLIOTECAS PARA O PROGRAMA
# @IMPORT DOCES
# @IMPORT BEBIDAS ---- IMPORTA TODA A BIBLIOTECA (GENÉRICO)

# @FROM DOCES IMPORT (PUDIM) ---- COMANDO PARA EXPORTAR ALGUM ITEM/FUNCIONALIDADE DENTRO DA BIBLIOTECA (ESPECÍFICO)


# @IMPORT (MATH)
# @CEIL (ARREDONDA PRA CIMA)
# @FLOOR (ARREDONDA PRA BAIXO)
# @TRUNC (ELIMINAR DEPOIS DA VÍRGULA)
# @POW (POTÊNCIA - SEMELHANTE A **)
# @SQRT (CALCULAR RAIZ QUADRADA)
# @FACTORIAL (CALCULO DE FATORIAL)

# @FROM MATH IMPORT SQRT (IMPORTAR SÓ UMA FUNÇÃO DA BIBLIOTECA 'MATH') (IMPORT SQRT, CEIL) -- PARA DUAS UTILIZAR VÍRGULA

from math import sqrt, floor
num = int(input('Digite um número: '))
raiz = sqrt(num)
print('A raiz quadrada de {:.2f} é igual a {:.2f}'.format(num, raiz))